
module.exports = {
  CART_LOAD: "CART_LOAD",
  CART_LOAD_SUCCESS: "CART_LOAD_SUCCESS",
  CART_LOAD_FAILURE: "CART_LOAD_FAILURE",

  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM"
};